# Example docker-compose.yml for slack-gpt with watchtower for auto-updates
version: '3.6'
services:
  slack-gpt:
    image: ghcr.io/prographers/slack-gpt:latest
    container_name: slack-gpt
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.scope=slack-gpt"
    volumes:
      # See appsettings.json.example for configuration this file is required
      - ./appsettings.json:/app/appsettings.json 
      - slack-gpt-liteDB:/app/app.db:rw

  watchtower-slack-gpt:
    image: containrrr/watchtower
    container_name: watchtower-slack-gpt
    restart: always
    volumes:
      - /root/.docker/config.json:/config.json
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 30 --scope slack-gpt
    
volumes:
  slack-gpt-liteDB:
